"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, ChevronLeft, ChevronRight, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label, Select, Textarea } from "@/components/ui/form-controls";
import { ARC_LABELS, ARC_TYPES } from "@/lib/constants";
import { cn } from "@/lib/utils";
import type { ArcType } from "@/types/database";
import { Turnstile } from "@/components/public/turnstile";
type Draft = Record<ArcType, { ministryAreaId: string; content: string }>;
export function ArcForm({ ministries, eventToken, turnstileSiteKey }: { ministries: { id: string; name: string }[]; eventToken: string; turnstileSiteKey: string }) { const router = useRouter(); const startedAt = useRef(0); const [selected, setSelected] = useState<ArcType[]>([]); const [draft, setDraft] = useState<Draft>({ affirmation: { ministryAreaId: "", content: "" }, recommendation: { ministryAreaId: "", content: "" }, correction: { ministryAreaId: "", content: "" } }); const [review, setReview] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [turnstileToken, setTurnstileToken] = useState(""); const valid = selected.length > 0 && selected.every((type) => draft[type].ministryAreaId && draft[type].content.trim().length >= 10);
  function toggle(type: ArcType) { startedAt.current ||= Date.now(); setSelected((current) => current.includes(type) ? current.filter((item) => item !== type) : [...current, type]); }
  async function submit() { setPending(true); setError(""); const response = await fetch("/api/public/arc", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ eventToken, startedAt: startedAt.current, website: "", turnstileToken, entries: selected.map((type) => ({ type, ...draft[type] })) }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "We could not submit your reflection."); setPending(false); return; } router.push("/thank-you?type=arc"); }
  if (review) return <Card><CardHeader><p className="eyebrow">Review your response</p><CardTitle>Ready to submit?</CardTitle></CardHeader><CardContent className="space-y-5">{selected.map((type) => <div key={type} className="rounded-xl bg-muted/70 p-5"><strong>{ARC_LABELS[type]}</strong><p className="mt-1 text-xs text-muted-foreground">{ministries.find((m) => m.id === draft[type].ministryAreaId)?.name}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{draft[type].content}</p></div>)}<p className="text-sm text-muted-foreground">This submission does not include your name, email, member ID, or account identifier.</p><Turnstile siteKey={turnstileSiteKey} onToken={setTurnstileToken}/>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-between gap-3"><Button variant="outline" onClick={() => setReview(false)}><ChevronLeft /> Edit</Button><Button onClick={submit} disabled={pending || Boolean(turnstileSiteKey && !turnstileToken)}>{pending ? <Loader2 className="animate-spin" /> : <Check />} Submit anonymously</Button></div></CardContent></Card>;
  return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-3">{ARC_TYPES.map((type) => <button key={type} onClick={() => toggle(type)} aria-pressed={selected.includes(type)} className={cn("rounded-xl border bg-card p-5 text-left transition", selected.includes(type) && "border-primary bg-secondary ring-2 ring-primary/15")}><span className="grid size-9 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground">{type[0].toUpperCase()}</span><strong className="mt-4 block">{ARC_LABELS[type]}</strong><span className="mt-1 block text-xs text-muted-foreground">{type === "affirmation" ? "What encouraged you?" : type === "recommendation" ? "What could we consider?" : "What needs care or change?"}</span></button>)}</div>{selected.map((type) => <Card key={type}><CardHeader><CardTitle>{ARC_LABELS[type]}</CardTitle></CardHeader><CardContent className="space-y-5"><div><Label htmlFor={`${type}-ministry`}>Ministry or area</Label><Select id={`${type}-ministry`} className="mt-2" value={draft[type].ministryAreaId} onChange={(e) => setDraft({ ...draft, [type]: { ...draft[type], ministryAreaId: e.target.value } })}><option value="">Select an area</option>{ministries.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</Select></div><div><Label htmlFor={`${type}-content`}>Your {type}</Label><Textarea id={`${type}-content`} className="mt-2" value={draft[type].content} maxLength={4000} placeholder="Share thoughtfully and specifically…" onChange={(e) => setDraft({ ...draft, [type]: { ...draft[type], content: e.target.value } })} /><p className="mt-1 text-right text-xs text-muted-foreground">{draft[type].content.length}/4000</p></div></CardContent></Card>)}<div className="flex justify-end"><Button size="lg" disabled={!valid} onClick={() => setReview(true)}>Review reflection <ChevronRight /></Button></div></div>;
}
