"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, LockKeyhole } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input, Label, Select, Textarea } from "@/components/ui/form-controls";
import { PRAYER_CATEGORIES, PRAYER_VISIBILITIES } from "@/lib/constants";
import { Turnstile } from "@/components/public/turnstile";
export function PrayerForm({ eventToken, turnstileSiteKey }: { eventToken: string; turnstileSiteKey: string }) { const router = useRouter(); const startedAt = useRef(0); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [turnstileToken, setTurnstileToken] = useState(""); const [anonymous, setAnonymous] = useState(false); const [visibility, setVisibility] = useState("prayer_team"); const [contactConsent, setContactConsent] = useState(false); const [shareConsent, setShareConsent] = useState(false);
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setPending(true); setError(""); const form = new FormData(e.currentTarget); const payload = { eventToken, startedAt: startedAt.current, website: form.get("website"), anonymous, name: anonymous ? "" : form.get("name"), request: form.get("request"), category: form.get("category"), visibility, contactConsent, contact: contactConsent ? form.get("contact") : "", shareConsent, turnstileToken }; const response = await fetch("/api/public/prayer", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "We could not submit your request."); setPending(false); return; } router.push("/thank-you?type=prayer"); }
  return <Card><CardHeader><CardTitle>Prayer request</CardTitle></CardHeader><CardContent><form onSubmit={submit} onFocusCapture={() => { startedAt.current ||= Date.now(); }} onPointerDown={() => { startedAt.current ||= Date.now(); }} className="space-y-6"><input name="website" className="hidden" tabIndex={-1} autoComplete="off" /><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={anonymous} onChange={(e) => setAnonymous(e.target.checked)} className="size-4 accent-primary" /> Submit anonymously</label>{!anonymous && <div><Label htmlFor="name">Name <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="name" name="name" className="mt-2" maxLength={120} /></div>}<div><Label htmlFor="request">Prayer request</Label><Textarea id="request" name="request" required minLength={10} maxLength={5000} className="mt-2 min-h-40" /></div><div><Label htmlFor="category">Category</Label><Select id="category" name="category" required className="mt-2"><option value="">Choose a category</option>{PRAYER_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</Select></div><div><Label htmlFor="visibility">Who may see this?</Label><Select id="visibility" name="visibility" value={visibility} onChange={(e) => setVisibility(e.target.value)} className="mt-2">{PRAYER_VISIBILITIES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</Select></div>{visibility === "congregation_review" && <label className="flex items-start gap-3 rounded-xl bg-accent/60 p-4 text-sm"><input required type="checkbox" checked={shareConsent} onChange={(e) => setShareConsent(e.target.checked)} className="mt-1 size-4 accent-primary" /><span>I consent to this request being considered for congregational sharing after administrative review. I understand it will not be published automatically.</span></label>}<div className="rounded-xl border p-4"><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={contactConsent} onChange={(e) => setContactConsent(e.target.checked)} className="mt-1 size-4 accent-primary" /><span>I consent to providing contact information for follow-up.</span></label>{contactConsent && <Input name="contact" required className="mt-3" placeholder="Phone number or email" maxLength={255} />}</div><div className="flex gap-3 rounded-xl bg-muted p-4 text-sm text-muted-foreground"><LockKeyhole className="size-5 shrink-0 text-primary" /><p>Sensitive details are restricted to authorized prayer care roles. We retain only information needed to provide care.</p></div><Turnstile siteKey={turnstileSiteKey} onToken={setTurnstileToken}/>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" size="lg" className="w-full" disabled={pending || Boolean(turnstileSiteKey && !turnstileToken)}>{pending && <Loader2 className="animate-spin" />} Submit prayer request</Button></form></CardContent></Card>;
}
