import Link from "next/link";
import { Plus } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { PageHeading } from "@/components/admin/page-heading";
import { Empty } from "@/components/admin/empty";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { archiveMember } from "@/app/admin/actions";
export default async function Members({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) { await requireAdmin(["super_admin","membership_admin"]); const { q = "", status = "" } = await searchParams; const db = await createClient(); let query = db.from("members").select("id,member_number,first_name,middle_name,last_name,contact_number,email,status,birthdate").eq("archived", false).order("last_name").limit(200); if (q) query = query.or(`first_name.ilike.%${q}%,last_name.ilike.%${q}%,member_number.ilike.%${q}%`); if (status) query = query.eq("status", status); const { data = [] } = await query; return <><PageHeading eyebrow="Directory" title="Church members" description="Personal information is restricted to authorized membership administrators." action={<Link href="/admin/members/new" className={buttonVariants({ size: "sm" })}><Plus /> Add member</Link>} /><form className="mb-5 flex gap-2"><input name="q" defaultValue={q} placeholder="Name or member ID" className="h-10 rounded-xl border bg-card px-3 text-sm" /><select name="status" defaultValue={status} className="h-10 rounded-xl border bg-card px-3 text-sm"><option value="">All statuses</option><option value="regular">Regular</option><option value="new">New</option><option value="visitor">Visitor</option><option value="inactive">Inactive</option></select><button className="rounded-xl bg-primary px-4 text-sm text-primary-foreground">Filter</button></form>{!(data ?? []).length ? <Empty title="No members found" /> : <div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead className="bg-muted/70 text-xs uppercase text-muted-foreground"><tr><th className="p-4">Member</th><th className="p-4">Contact</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{(data ?? []).map((m) => <tr key={m.id} className="border-t"><td className="p-4"><strong>{m.last_name}, {m.first_name}</strong><span className="block text-xs text-muted-foreground">{m.member_number}</span></td><td className="p-4">{m.contact_number}<span className="block text-xs text-muted-foreground">{m.email}</span></td><td className="p-4"><Badge className="capitalize">{m.status}</Badge></td><td className="p-4"><div className="flex gap-3"><Link href={`/admin/members/${m.id}`} className="text-primary underline">Edit</Link><form action={archiveMember}><input type="hidden" name="id" value={m.id}/><button className="text-destructive underline">Archive</button></form></div></td></tr>)}</tbody></table></div>}</>; }
